[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "su -s /bin/sh nobody -c \"node /app/dist/server/src/index.js\""
healthcheckPath = "/setup/healthz"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
